name:                minesweeper
version:             0.1.0.0
github:              "DKurilo/minesweeper"
license:             BSD3
author:              "Dima Kurilo"
maintainer:          "dkurilo@gmail.com"
copyright:           "Dima Kurilo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            games

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/DKurilo/minesweeper#readme>

dependencies:
- base               >= 4.7 && < 5
- brick              >= 0.47 && < 0.51
- optparse-generic   >= 1.3  && < 1.4
- text               >= 1.2 && < 1.3
- random             >= 1.1 && < 1.2
- lens               >= 4.17 && < 4.19
- containers         >= 0.6 && < 0.7
- vty                >= 5.25 && < 5.26

library:
  source-dirs: src

executables:
  minesweeper:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minesweeper
    - brick              >= 0.47 && < 0.51
    - optparse-generic   >= 1.3  && < 1.4

tests:
  minesweeper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minesweeper
